### ISSUE TITLE
Verifications System Error while using it

### ISSUE THREAD

**Issue by Bloxcrafter1** [rwolf2467/baxi#3]
While I test the verification System from BAXI is there an Error, when you thry to send the verification to BAXI. In the folowing picture shoud be an good discription.
![image](https://github.com/user-attachments/assets/078611bb-24f2-4b81-b0f3-995ddfe3b3d5)

**Comment by rwolf2467** [comment]
Possible fix found! Patch is now on the server and live.

**Comment by rwolf2467** [comment]
Bug Fixed
